require_relative '../models/question'
require_relative '../models/option'

Question.create(description: 'Cuál es el animal más rápido del mundo?', asked: false)
Option.create(description: 'El halcón peregrino', isCorrect: true, question_id: 1)
Option.create(description: 'El guepardo', isCorrect: false, question_id: 1)
Option.create(description: 'El antílope', isCorrect: false, question_id: 1)
Option.create(description: 'El tigre siberiano', isCorrect: false, question_id: 1)
Question.create(description: 'Qué pájaro pone el huevo más pequeño?', asked: false)
Option.create(description: 'El colibrí', isCorrect: true, question_id: 2)
Option.create(description: 'El chipe azul', isCorrect: false, question_id: 2)
Option.create(description: 'El jilguero', isCorrect: false, question_id: 2)
Option.create(description: 'La paloma', isCorrect: false, question_id: 2)
# Question.create(description: , asked: false)
# Option.create(description: , isCorrect: , question_id: 3)
# Option.create(description: , isCorrect: , question_id: 3)
# Option.create(description: , isCorrect: , question_id: 3)
# Option.create(description: , isCorrect: , question_id: 3)
# Question.create(description: , asked: false)
# Option.create(description: , isCorrect: , question_id: 4)
# Option.create(description: , isCorrect: , question_id: 4)
# Option.create(description: , isCorrect: , question_id: 4)
# Option.create(description: , isCorrect: , question_id: 4)
# Question.create(description: , asked: false)
# Option.create(description: , isCorrect: , question_id: 5)
# Option.create(description: , isCorrect: , question_id: 5)
# Option.create(description: , isCorrect: , question_id: 5)
# Option.create(description: , isCorrect: , question_id: 5)