require_relative '../models/question'
require_relative '../models/option'

Question.create(description: 'Cuál es el animal más rápido del mundo?', asked: false)
Option.create(description: 'El halcón peregrino', type: true, question_id: 1)
Option.create(description: 'El guepardo', type: false, question_id: 1)
Option.create(description: 'El antílope', type: false, question_id: 1)
Option.create(description: 'El tigre siberiano', type: false, question_id: 1)
Question.create(description: 'Qué pájaro pone el huevo más pequeño?', asked: false)
Option.create(description: 'El colibrí', type: true, question_id: 2)
Option.create(description: 'El chipe azul', type: false, question_id: 2)
Option.create(description: 'El jilguero', type: false, question_id: 2)
Option.create(description: 'La paloma', type: false, question_id: 2)
# Question.create(description: , asked: false)
# Option.create(description: , type: , question_id: 3)
# Option.create(description: , type: , question_id: 3)
# Option.create(description: , type: , question_id: 3)
# Option.create(description: , type: , question_id: 3)
# Question.create(description: , asked: false)
# Option.create(description: , type: , question_id: 4)
# Option.create(description: , type: , question_id: 4)
# Option.create(description: , type: , question_id: 4)
# Option.create(description: , type: , question_id: 4)
# Question.create(description: , asked: false)
# Option.create(description: , type: , question_id: 5)
# Option.create(description: , type: , question_id: 5)
# Option.create(description: , type: , question_id: 5)
# Option.create(description: , type: , question_id: 5)