ruby '2.7.5'

source "https://rubygems.org"

gem 'multi_json'

github 'sinatra/sinatra' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end

gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'simplecov'
gem 'bcrypt'
gem 'mail'
gem 'rubocop', '~> 0.91.0', require: false


group :test do
  gem 'rspec'
end